## Leitura de dados

In [1]:
# bibliotecas 
import csv
import pandas as pd

In [2]:
dados = []
path = '../data_raw/stores_sales_forecasting.csv'

with open(path, 'r', encoding='latin-1') as file:
    reader = csv.DictReader(file, delimiter=',')
    for row in reader:
        dados.append(row)

In [3]:
dados[1]

{'Row ID': '2',
 'Order ID': 'CA-2016-152156',
 'Order Date': '11/8/2016',
 'Ship Date': '11/11/2016',
 'Ship Mode': 'Second Class',
 'Customer ID': 'CG-12520',
 'Customer Name': 'Claire Gute',
 'Segment': 'Consumer',
 'Country': 'United States',
 'City': 'Henderson',
 'State': 'Kentucky',
 'Postal Code': '42420',
 'Region': 'South',
 'Product ID': 'FUR-CH-10000454',
 'Category': 'Furniture',
 'Sub-Category': 'Chairs',
 'Product Name': 'Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back',
 'Sales': '731.94',
 'Quantity': '3',
 'Discount': '0',
 'Profit': '219.582'}

In [4]:
dados[0].keys()

dict_keys(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'])

## Ajustando nome das colunas

In [5]:
key_mapping = {
    'Row ID': 'ID Registro',
    'Order ID': 'ID Pedido',
    'Order Date': 'Data do Pedido',
    'Ship Date': 'Data de Envio Pedido',
    'Ship Mode': 'Modo de Envio Pedido',
    'Customer ID': 'ID Cliente',
    'Customer Name': 'Nome Cliente',
    'Segment': 'Classificacao Cliente',
    'Country': 'Pais Venda',
    'City': 'Cidade Venda',
    'State': 'Estado Venda',
    'Postal Code': 'Codigo Postal Venda',
    'Region': 'Regiao Venda',
    'Product ID': 'ID Produto',
    'Category': 'Categoria Produto',
    'Sub-Category': 'Sub-Categoria Produto',
    'Product Name': 'Nome Produto',
    'Sales': 'Venda Total',
    'Quantity': 'Quantidade Vendida',
    'Discount': 'Desconto Aplicado',
    'Profit': 'Lucro Obtido'
}

novos_dados = []
for antigo in dados:
    dicionario_temporario = {}
    for chave_antiga, valor in antigo.items():
        dicionario_temporario[key_mapping[chave_antiga]] = valor
    novos_dados.append(dicionario_temporario)

In [6]:
# Visualizando dados com chaves renomeadas
novos_dados[0]

{'ID Registro': '1',
 'ID Pedido': 'CA-2016-152156',
 'Data do Pedido': '11/8/2016',
 'Data de Envio Pedido': '11/11/2016',
 'Modo de Envio Pedido': 'Second Class',
 'ID Cliente': 'CG-12520',
 'Nome Cliente': 'Claire Gute',
 'Classificacao Cliente': 'Consumer',
 'Pais Venda': 'United States',
 'Cidade Venda': 'Henderson',
 'Estado Venda': 'Kentucky',
 'Codigo Postal Venda': '42420',
 'Regiao Venda': 'South',
 'ID Produto': 'FUR-BO-10001798',
 'Categoria Produto': 'Furniture',
 'Sub-Categoria Produto': 'Bookcases',
 'Nome Produto': 'Bush Somerset Collection Bookcase',
 'Venda Total': '261.96',
 'Quantidade Vendida': '2',
 'Desconto Aplicado': '0',
 'Lucro Obtido': '41.9136'}

## Transformando lista em dataframe

In [7]:
ecommerce_df = pd.DataFrame(novos_dados)
ecommerce_df.head()

,ID Registro,ID Pedido,Data do Pedido,Data de Envio Pedido,Modo de Envio Pedido,ID Cliente,Nome Cliente,Classificacao Cliente,Pais Venda,Cidade Venda,...,Codigo Postal Venda,Regiao Venda,ID Produto,Categoria Produto,Sub-Categoria Produto,Nome Produto,Venda Total,Quantidade Vendida,Desconto Aplicado,Lucro Obtido
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0,219.582
2,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.031
3,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.86,7,0,14.1694
4,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.184,9,0.2,85.3092

In [8]:
ecommerce_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2121 entries, 0 to 2120
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID Registro            2121 non-null   object
 1   ID Pedido              2121 non-null   object
 2   Data do Pedido         2121 non-null   object
 3   Data de Envio Pedido   2121 non-null   object
 4   Modo de Envio Pedido   2121 non-null   object
 5   ID Cliente             2121 non-null   object
 6   Nome Cliente           2121 non-null   object
 7   Classificacao Cliente  2121 non-null   object
 8   Pais Venda             2121 non-null   object
 9   Cidade Venda           2121 non-null   object
 10  Estado Venda           2121 non-null   object
 11  Codigo Postal Venda    2121 non-null   object
 12  Regiao Venda           2121 non-null   object
 13  ID Produto             2121 non-null   object
 14  Categoria Produto      2121 non-null   object
 15  Sub-Categoria Produto  2121 non-null   object
 16  Nome Produto           2121 non-null   object
 17  Venda Total            2121 non-null   object
 18  Quantidade Vendida     2121 non-null   object
 19  Desconto Aplicado      2121 non-null   object
 20  Lucro Obtido           2121 non-null   object
dtypes: object(21)
memory usage: 348.1+ KB

Nas colunas 'Venda Total', 'Desconto Aplicado' e 'Lucro Obtido' será necessário a transformação do tipo para float, e 'Quantidade Vendida' para inteiro. <br>
Também será necessário ajustar os tipos das Datas de Pedido e Envio

In [9]:
# Verificando se há valores nulos
ecommerce_df.isnull().sum()

ID Registro              0
ID Pedido                0
Data do Pedido           0
Data de Envio Pedido     0
Modo de Envio Pedido     0
ID Cliente               0
Nome Cliente             0
Classificacao Cliente    0
Pais Venda               0
Cidade Venda             0
Estado Venda             0
Codigo Postal Venda      0
Regiao Venda             0
ID Produto               0
Categoria Produto        0
Sub-Categoria Produto    0
Nome Produto             0
Venda Total              0
Quantidade Vendida       0
Desconto Aplicado        0
Lucro Obtido             0
dtype: int64

## Ajustando Tipos de Dados

In [10]:
# Ajustando tipo de dados da coluna 'Venda Total', 'Desconto Aplicado' e 'Lucro Obtido' para flutuante
ecommerce_df['Venda Total'] = ecommerce_df['Venda Total'].astype(float)
ecommerce_df['Desconto Aplicado'] = ecommerce_df['Desconto Aplicado'].astype(float)
ecommerce_df['Lucro Obtido'] = ecommerce_df['Lucro Obtido'].astype(float)

In [11]:
# Ajustando tipo de dados da coluna 'Quantidade Vendida' para inteiro
ecommerce_df['Quantidade Vendida'] = ecommerce_df['Quantidade Vendida'].astype(int)

In [12]:
# Ajustando tipo de dados da coluna 'Data do Pedido' e 'Data de Envio Pedido' para datetime
ecommerce_df['Data do Pedido'] = pd.to_datetime(ecommerce_df['Data do Pedido'], format='%m/%d/%Y')
ecommerce_df['Data de Envio Pedido'] = pd.to_datetime(ecommerce_df['Data de Envio Pedido'], format='%m/%d/%Y')

In [13]:
ecommerce_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2121 entries, 0 to 2120
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID Registro            2121 non-null   object
 1   ID Pedido              2121 non-null   object
 2   Data do Pedido         2121 non-null   datetime64[ns]
 3   Data de Envio Pedido   2121 non-null   datetime64[ns]
 4   Modo de Envio Pedido   2121 non-null   object
 5   ID Cliente             2121 non-null   object
 6   Nome Cliente           2121 non-null   object
 7   Classificacao Cliente  2121 non-null   object
 8   Pais Venda             2121 non-null   object
 9   Cidade Venda           2121 non-null   object
 10  Estado Venda           2121 non-null   object
 11  Codigo Postal Venda    2121 non-null   object
 12  Regiao Venda           2121 non-null   object
 13  ID Produto             2121 non-null   object
 14  Categoria Produto      2121 non-null   object
 15  Sub-Categoria Produto  2121 non-null   object
 16  Nome Produto           2121 non-null   object
 17  Venda Total            2121 non-null   float64
 18  Quantidade Vendida     2121 non-null   int64
 19  Desconto Aplicado      2121 non-null   float64
 20  Lucro Obtido           2121 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(1), object(15)
memory usage: 348.1+ KB

In [14]:
ecommerce_df

,ID Registro,ID Pedido,Data do Pedido,Data de Envio Pedido,Modo de Envio Pedido,ID Cliente,Nome Cliente,Classificacao Cliente,Pais Venda,Cidade Venda,...,Codigo Postal Venda,Regiao Venda,ID Produto,Categoria Produto,Sub-Categoria Produto,Nome Produto,Venda Total,Quantidade Vendida,Desconto Aplicado,Lucro Obtido
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
3,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
4,11,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2116,9963,CA-2015-168088,2015-03-19,2015-03-22,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,...,77041,Central,FUR-BO-10004218,Furniture,Bookcases,Bush Heritage Pine Collection 5-Shelf Bookcase...,383.4656,4,0.32,-67.6704
2117,9965,CA-2016-146374,2016-12-05,2016-12-10,Second Class,HE-14800,Harold Engle,Corporate,United States,Newark,...,19711,East,FUR-FU-10002671,Furniture,Furnishings,Electrix 20W Halogen Replacement Bulb for Zoom...,13.4000,1,0.00,6.4320
2118,9981,US-2015-151435,2015-09-06,2015-09-09,Second Class,SW-20455,Shaun Weien,Consumer,United States,Lafayette,...,70506,South,FUR-TA-10001039,Furniture,Tables,KI Adjustable-Height Table,85.9800,1,0.00,22.3548
2119,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
2120,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332

In [15]:
ecommerce_df['ID Registro'].drop_duplicates()

0          1
1          2
2          4
3          6
4         11
        ...
2116    9963
2117    9965
2118    9981
2119    9990
2120    9991
Name: ID Registro, Length: 2121, dtype: object

## Salvando Dados

In [23]:
ecommerce_df.to_csv('../data_processed/stores_sales_forecasting_tratado.csv', index=False, encoding='utf-8')